name: test

on: [push]

jobs:
    test:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3
              with:
                submodules: 'true'

            - name: Dependencies
              run: |
                sudo apt-get update && \
                sudo apt-get install -y \
                  build-essential \
                  cmake \
                  glslang-dev \
                  glslang-tools \
                  libglfw3-dev \
                  libvulkan-dev \
                  spirv-tools \
                  vulkan-tools \
                  vulkan-validationlayers-dev

            - name: Build
              run: make build
